# This file was generated by GoReleaser. DO NOT EDIT.
cask "chagg" do
  version "0.14.5"

  on_macos do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-amd64"
      sha256 "c6cb019f56985c77a02caf8fdd646c5bb276cb5fd24f31971bff55e2454c2deb"
      binary "chagg-darwin-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-arm64"
      sha256 "5030f51ee549eaacd90c296f0fda1fabcf8e31c1bc2d07d936a258bc60d5d36c"
      binary "chagg-darwin-arm64", target: "chagg"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-amd64"
      sha256 "a5449cd055a522faabbb836b8de44c705a7e407ac7afe42034d86cb47bb5d075"
      binary "chagg-linux-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-arm64"
      sha256 "4d5add9a91f01809fb3bf2d12db031b1043f7ae9ec5a9d2f719aaf5448cbaa48"
      binary "chagg-linux-arm64", target: "chagg"
    end
  end

  name "chagg"
  desc "A modern release-note workflow tool"
  homepage "https://chagg.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
