# This file was generated by GoReleaser. DO NOT EDIT.
cask "chagg" do
  name "chagg"
  desc "A modern release-note workflow tool"
  homepage "https://chagg.dev"
  version "0.14.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-amd64"
      sha256 "02bc88027e9e63b8ace5b980817a39c9003b551692ed2d496e4e8fa0623c5560"
      binary "chagg-darwin-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-arm64"
      sha256 "412c5d398725acc7c8826c60053ff124f7bdd6d817f310b4a8e6b8949398b834"
      binary "chagg-darwin-arm64", target: "chagg"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-amd64"
      sha256 "b325645869c39e21b7d48b0c6944713f02c85b4fac4c58c331d1b8b231fada50"
      binary "chagg-linux-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-arm64"
      sha256 "9f52fa414c2548c8618939d8a0d1f93ba2e8ccbd997d024b5da8e2ecd511c9d0"
      binary "chagg-linux-arm64", target: "chagg"
    end
  end

  # No zap stanza required
end
