# This file was generated by GoReleaser. DO NOT EDIT.
cask "chagg" do
  name "chagg"
  desc "A modern release-note workflow tool"
  homepage "https://chagg.dev"
  version "0.14.3"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-amd64"
      sha256 "d81bd3db332ab26c36bf55f06be922ef70ffc33e868f04e757fa58d3b5aba279"
      binary "chagg-darwin-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-darwin-arm64"
      sha256 "8fa2ce11bcdbddd9e313db66907b4b4d69a3246426c39f76829c8fe0093699d1"
      binary "chagg-darwin-arm64", target: "chagg"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-amd64"
      sha256 "4f644fe03960c0ac605dde8aba72818158cc05f491137f4eb6278541c39f5bcc"
      binary "chagg-linux-amd64", target: "chagg"
    end
    on_arm do
      url "https://github.com/codested/chagg/releases/download/#{version}/chagg-linux-arm64"
      sha256 "36679096b0750406124e1c4e0672cef84cb76d17a6d5553c53bb92c22ad2f03b"
      binary "chagg-linux-arm64", target: "chagg"
    end
  end

  # No zap stanza required
end
